#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CLASSES_DIR=$SCRIPT_DIR/classes
TMP_DIR=/tmp/intellij14eap-jar
JAR_FILE="/Applications/IntelliJ IDEA 14.app/Contents/lib/idea.jar"
JAR_FILE_MD5=$(md5 "$JAR_FILE" | awk '{ print ( $NF ) }')

echo 'MD5 of jar file: '$JAR_FILE_MD5

if [ "$JAR_FILE_MD5" = "8d745efd14c998a2eead0ef525d1e38d" ]
then
    rm -rf $TMP_DIR
    mkdir $TMP_DIR
    mkdir $TMP_DIR/idea
    cd $TMP_DIR/idea
    jar xf "$JAR_FILE"
    cp "$CLASSES_DIR/EditorSearchComponent"*.class "$TMP_DIR"/idea/com/intellij/find
    cp "$CLASSES_DIR/CloseOn"*.class "$TMP_DIR"/idea/com/intellij/find/editorHeaderActions

    jar cf0 ../idea.jar .

    mv "$JAR_FILE" "$JAR_FILE.original"
    cp ../idea.jar "$JAR_FILE"

    rm -rf $TMP_DIR
else
    echo 'idea.jar failed MD5.  Has it been modified already?  Is this a pre-14.1 version?'
fi
